export { default as Gainers } from './gainers'
export { default as HighMarketCap } from './high-market-cap'
export { default as HighVolume } from './high-volume'
export { default as Main } from './main'
export { default as Losers } from './losers'
export { default as NewCoin } from './new-coin'
export { default as Search } from './search'
