export { default as Gainers } from './gainers'
export { default as HighMarkeCap } from './highMarketCap'
export { default as HighVolume } from './highVolume'
export { default as Main } from './main'
export { default as Losers } from './losers'
export { default as NewCoin } from './newCoin'
export { default as Search } from './search'
